#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-lazyeval
Version  : 0.2.0
Release  : 2
URL      : https://cran.r-project.org/src/contrib/lazyeval_0.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lazyeval_0.2.0.tar.gz
Summary  : Lazy (Non-Standard) Evaluation
Group    : Development/Tools
License  : GPL-3.0
Requires: R-lazyeval-lib
Requires: R-mime
BuildRequires : R-mime
BuildRequires : clr-R-helpers

%description
# lazyeval
[![Build Status](https://travis-ci.org/hadley/lazyeval.png?branch=master)](https://travis-ci.org/hadley/lazyeval)
[![Coverage Status](https://img.shields.io/codecov/c/github/hadley/lazyeval/master.svg)](https://codecov.io/github/hadley/lazyeval?branch=master)

%package lib
Summary: lib components for the R-lazyeval package.
Group: Libraries

%description lib
lib components for the R-lazyeval package.


%prep
%setup -q -c -n lazyeval

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1493411071

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1493411071
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lazyeval
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library lazyeval


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lazyeval/DESCRIPTION
/usr/lib64/R/library/lazyeval/INDEX
/usr/lib64/R/library/lazyeval/Meta/Rd.rds
/usr/lib64/R/library/lazyeval/Meta/features.rds
/usr/lib64/R/library/lazyeval/Meta/hsearch.rds
/usr/lib64/R/library/lazyeval/Meta/links.rds
/usr/lib64/R/library/lazyeval/Meta/nsInfo.rds
/usr/lib64/R/library/lazyeval/Meta/package.rds
/usr/lib64/R/library/lazyeval/Meta/vignette.rds
/usr/lib64/R/library/lazyeval/NAMESPACE
/usr/lib64/R/library/lazyeval/NEWS.md
/usr/lib64/R/library/lazyeval/R/lazyeval
/usr/lib64/R/library/lazyeval/R/lazyeval.rdb
/usr/lib64/R/library/lazyeval/R/lazyeval.rdx
/usr/lib64/R/library/lazyeval/doc/index.html
/usr/lib64/R/library/lazyeval/doc/lazyeval-old.R
/usr/lib64/R/library/lazyeval/doc/lazyeval-old.Rmd
/usr/lib64/R/library/lazyeval/doc/lazyeval-old.html
/usr/lib64/R/library/lazyeval/doc/lazyeval.R
/usr/lib64/R/library/lazyeval/doc/lazyeval.Rmd
/usr/lib64/R/library/lazyeval/doc/lazyeval.html
/usr/lib64/R/library/lazyeval/help/AnIndex
/usr/lib64/R/library/lazyeval/help/aliases.rds
/usr/lib64/R/library/lazyeval/help/lazyeval.rdb
/usr/lib64/R/library/lazyeval/help/lazyeval.rdx
/usr/lib64/R/library/lazyeval/help/paths.rds
/usr/lib64/R/library/lazyeval/html/00Index.html
/usr/lib64/R/library/lazyeval/html/R.css
/usr/lib64/R/library/lazyeval/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/lazyeval/libs/lazyeval.so
